networks:
  traefik_network:
    driver: bridge

services:

  plex:

    container_name: "plex"

    entrypoint:
      - "/init"

    environment:
      - "DEBIAN_FRONTEND=noninteractive"
      - "HOME=/root"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
      - "LSIO_FIRST_PARTY=true"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=1000"
      - "PLEX_ARCH=amd64"
      - "PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new"
      - "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support"
      - "PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver"
      - "PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)"
      - "PLEX_MEDIA_SERVER_INFO_VENDOR=Docker"
      - "PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6"
      - "PLEX_MEDIA_SERVER_USER=abc"
      - "PUID=1000"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "S6_VERBOSITY=1"
      - "TERM=xterm"
      - "VIRTUAL_ENV=/lsiopy"

    expose:
      - "1900/udp"
      - "3005/tcp"
      - "32400/tcp"
      - "32410/udp"
      - "32412/udp"
      - "32413/udp"
      - "32414/udp"
      - "32469/tcp"
      - "5353/udp"
      - "8324/tcp"

    hostname: "saarver"

    image: "linuxserver/plex:latest"

    ipc: "private"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    restart: "unless-stopped"

    volumes:
      - "/var/lib/plexmediaserver/movies:/movies"
      - "/var/lib/plexmediaserver/music:/music"
      - "/var/lib/plexmediaserver/tv:/tv"
      - "plex_config:/config"

    working_dir: "/"

  portainer:

    container_name: "portainer"

    entrypoint:
      - "/portainer"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    hostname: "05d3d369724e"

    image: "portainer/portainer-ce:latest"

    ipc: "private"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "bridge"

    ports:
      - "8000:8000/tcp"
      - "9443:9443/tcp"

    restart: "always"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

    working_dir: "/"

  transmission:

    container_name: "transmission"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "8d19153a49ab"

    image: "linuxserver/transmission:latest"

    ipc: "private"

    labels:
      traefik.enable: "true"
      traefik.http.routers.transmission.rule: "Host(`transmission.saarkoren.com`)"
      traefik.http.routers.transmission.entrypoints: "websecure"
      traefik.http.services.transmission.loadbalancer.server.port: "9091"
      traefik.http.routers.transmission.tls.certresolver: "myresolver"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - traefik_network

    ports:
      - "51413:51413/tcp"
      - "51413:51413/udp"
      - "9091:9091/tcp"

    restart: "unless-stopped"

    volumes:
      - "/home/saar/Downloads/transmission:/downloads"
      - "transmission_config:/config"
      - "transmission_watch:/watch"

    working_dir: "/"

  traefik:

    container_name: "traefik"

    image: "traefik:latest"

    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=saarkoren6@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      
    networks:
      - traefik_network

    labels:
      - "traefik.http.routers.api.rule=Host(`saarkoren.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

volumes:
  plex_config:
    external: true
  portainer_data:
    external: true
  transmission_config:
    external: true
  transmission_watch:
    external: true
