name: plex

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: "plex"
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Israel
      - VERSION=docker
    volumes:
      - "/srv/plex/movies:/movies"
      - "/srv/plex/music:/music"
      - "/srv/plex/tv:/tv"
      - "/srv/plex/config:/config"
    restart: "unless-stopped"

volumes:
  plex_config:
    external: true
