services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/saar/docker/prometheus/data:/prometheus
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "19090:9090"
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true
