networks:
  traefik_network:
    driver: bridge
    name: traefik_network

services:
  traefik:
    container_name: "traefik"
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=saarkoren6@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    environment:
      - CF_DNS_API_TOKEN=f9lDwKM6h3z6kNY_n_YmGFW96I5E2bb3elWUb2Vt
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/saar/docker/traefik/letsencrypt:/letsencrypt"
    networks:
      - traefik_network
    labels:
      - "traefik.http.routers.api.rule=Host(`saarkoren.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

