services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Israel
    volumes:
      - /home/saar/docker/nextcloud/appdata:/config
      - /home/saar/docker/nextcloud/data:/data
    ports:
     - 443:443
    restart: unless-stopped

