services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Israel
    volumes:
      - /home/saar/docker/rss/config:/config
    ports:
      - 9090:80
    restart: unless-stopped
