services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/run/secrets/newt-config
    secrets:
      - newt-config
    networks:
      - nextcloud-aio

secrets:
  newt-config:
    file: secrets/newt-config.secret

networks:
  nextcloud-aio:
    external: true
